### ISSUE TITLE
实验结果差距很大，请问是什么原因？

### ISSUE THREAD

**Issue by JunnYu** [MrZixi/SentiPrompt#1]
您好，以下是我使用本仓库代码替换随机种子重复5次跑出的实验结果，感觉实验结果与论文中汇报的结果差距有点大，请问能提供一下详细的训练命令代码吗？
```sh
task="penga/14lap penga/14res penga/15res penga/16res pengb/14lap pengb/14res pengb/15res pengb/16res lcx/14lap lcx/14res lcx/15res lcx/16res"
s="544 3210 8 5678 744"
for SEED in $s
do
for dataset in $task
do
LOG_DIR=/mnt/f/yj/senti/logs_prompt_type3bs16/$dataset/$SEED
python train.py --dataset_name $dataset \
                                       --log_dir $LOG_DIR \
                                       --batch_size 32 \
                                       --lr 5e-5 \
                                       --n_epochs 50 \
                                       --save_model $LOG_DIR/models \
                                       --prompt type3 \
                                       --seed $SEED
done
done
```
|      ds     | test_aesc_f1_mean | test_pair_f1_mean | test_f1_mean | test_precision_mean | test_recall_mean |
|-------------|-------------------|-------------------|--------------|---------------------|------------------|
| penga_14lap |        65.3       |       58.59       |    54.48     |        64.43        |       47.2       |
| penga_14res |       76.19       |       74.02       |    69.96     |        72.69        |      67.42       |
| penga_15res |       66.32       |       64.76       |    55.55     |         61.7        |      50.51       |
| penga_16res |       74.94       |       72.99       |    67.89     |        70.64        |      65.36       |

|      ds     | test_aesc_f1_mean | test_pair_f1_mean | test_f1_mean | test_precision_mean | test_recall_mean |
|-------------|-------------------|-------------------|--------------|---------------------|------------------|
| pengb_14lap |       68.42       |       61.09       |    55.25     |        60.22        |      51.04       |
| pengb_14res |       78.59       |       72.26       |    69.01     |        70.61        |      67.49       |
| pengb_15res |       67.19       |       62.19       |    53.49     |        59.96        |      48.29       |
| pengb_16res |       73.11       |       70.07       |     65.8     |        70.94        |      61.37       |

|     ds    | test_aesc_f1_mean | test_pair_f1_mean | test_f1_mean | test_precision_mean | test_recall_mean |
|-----------|-------------------|-------------------|--------------|---------------------|------------------|
| lcx_14lap |       67.12       |       55.59       |    51.64     |        57.75        |       46.7       |
| lcx_14res |       75.56       |       64.84       |    60.99     |        63.45        |      58.73       |
| lcx_15res |       68.63       |       56.04       |    51.25     |        55.15        |      47.88       |
| lcx_16res |       76.25       |       68.69       |    64.06     |        67.66        |      60.83       |

**Comment by MrZixi** [comment]
抱歉由于我们的文章仍在审，所以公布的实现仅是比较早期的一个示例，并不是最终取得文中较好结果的代码和训练脚本。感谢您的提醒，我们将先隐去代码，仅保留公布的数据集。
